[project]
name = "music-downloader"
version = "0.1.0"
description = "Music downloader api from youtube using yt-dlp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydub>=0.25.1",
    "yt-dlp>=2025.4.30",
]
